### ISSUE TITLE
Strange handling of +

### ISSUE THREAD

**Issue by DavidNemeskey** [dlt-rilmta/quntoken#13]
C++ is parsed as `<w>C</w><c>++</c>`, even though it should be a single token `<w>C++</w>`. Also, I am not sure these are consistent:
- `2+ 3 -> <w>2</w><c>+</c><ws> </ws><w>3</w>`
- `2+3 -> <w>2</w><w>+3</w>`
- `2 +3 -> <w>2</w><ws> </ws><w>+3</w>`
- `2-3 -> <w>2-3</w>`
- `2*3 -> <w>2</w><c>*</c><w>3</w>`

I see why `+3` is a token and `2+` is not, but I think `2+3` should rather be `<w>2</w> <c>+</c> <w>3</w>`.

**Comment by m-ivan** [comment]
Bugs like 'C++' and '2+3' have been fixed.
Operations with '/' and '-' signs are unchanged for keeping the date expressions as one token.
