### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by DavidNemeskey** [dlt-rilmta/quntoken#14]
```
echo 'P. L.' > tst
bin/quntoken tst
```
Et voilà.

**Comment by DavidNemeskey** [comment]
Great! Now it seems to work. If you allow a suggestion, I would make it clear in the `.qx` file why these were needed and also change _fajlveg_ to _bekezdes vege_ or something like that, as that is where the segfault happened. Maybe also add such an example to one of the tests?

**Comment by m-ivan** [comment]
Done.

**Comment by DavidNemeskey** [comment]
:+1:
