### ISSUE TITLE
No rest for the weary

### ISSUE THREAD

**Issue by DavidNemeskey** [dlt-rilmta/quntoken#18]
More segfaults. I think the latest commit introduced some regressions...
[segfaults.txt](https://github.com/dlt-rilmta/quntoken/files/642391/segfaults.txt)

**Comment by m-ivan** [comment]
@DavidNemeskey Maybe it is fixed. Pleas check it out.

**Comment by DavidNemeskey** [comment]
No segfaults on the [Webcorpus](http://mokk.bme.hu/resources/webcorpus/). Great job!
