### ISSUE TITLE
URLs should be kept as a single token

### ISSUE THREAD

**Issue by DavidNemeskey** [dlt-rilmta/quntoken#19]
The URL in the sentence _Abban az esetben, ha a - fiktív - www.kereso.elte.hu szervertől kérjük a www.kereso.elte.hu/nev=kiss,jozsef%kar=jog%tagozat=nappali címen található oldalt, akkor az elképzelt kiszolgálónk a kérésre megmutatná a megnevezett egyetemi hallgatóról rendelkezésre álló adatokat._ is split into several tokens:

```
<w>www.kereso.elte.hu/nev</w>
<c>=</c>
<w>kiss</w>
<c>,</c>
<w>jozsef%kar</w>
<c>=</c>
<w>jog%tagozat</w>
<c>=</c>
<w>nappali</w>
```

I think URLs should be just left as is.

**Comment by DavidNemeskey** [comment]
Also, if not too difficult, it would be nice to have it as a different token type (or "kind" in [GATE](https://github.com/dlt-rilmta/hunlp-GATE)): either as `<u>url</u>` or `<w type="url">url</w>`.

**Comment by m-ivan** [comment]
There is intentionally no 'URL' tag, 'e-mail' tag, 'date' tag, etc. Maybe later will be a more detailed annotation, but not now.

**Comment by DavidNemeskey** [comment]
You are right, a separate tag would probably not make sense; however, an optional `type` field would be very useful.

**Comment by m-ivan** [comment]
OK. Can you open a new issue for this?
