### ISSUE TITLE
Hyphens

### ISSUE THREAD

**Issue by DavidNemeskey** [dlt-rilmta/quntoken#21]
Tokens like _Pécs-Nagykanizsa-Graz-Aussee-Ischl-Salzburg-Zürich-Luzern-Rigire-Zürich-München-Linz-Bécs-Győr-Mohács-Pécs_ should probably be split into _Pécs - Nagykanizsa - ..._

**Comment by m-ivan** [comment]
@DavidNemeskey There is a new rule for enumerations containing at least three items, being capitalized and hyphenated.
(see 9a20659)

**Comment by DavidNemeskey** [comment]
Doesn't work if the enumeration is the last token in the sentence, e.g.
_Mondanunk sem kell, mennyi szervezésbe-levelezésbe került, amíg rögzítették az útvonalat: Pécs-Nagykanizsa-Graz-Aussee-Ischl-Salzburg-Zürich-Luzern-Rigire-Zürich-München-Linz-Bécs-Győr-Mohács-Pécs._
