### ISSUE TITLE
Unicode spaces are treated as punctuation

### ISSUE THREAD

**Issue by DavidNemeskey** [dlt-rilmta/quntoken#27]
See the attached file. In e.g. Python, `text[71].isspace() == True`. Yet quntoken fails to recognize it as such.
[unicode_space.txt](https://github.com/dlt-rilmta/quntoken/files/847578/unicode_space.txt)

**Comment by m-ivan** [comment]
text[71] is an ideographic space (U+3000), which is a CJK character. QunToken deals only with Latin, Cyrillic and Greek characters and symbols. All other characters are now replaced with a "replacement character" (U+FFFD), which is treated as a punctuation sign.
This approach can be changed in the future if needed.

**Comment by DavidNemeskey** [comment]
I understand that supporting arbitrary Unicode characters would be an enormous and task with very low return. However, spaces are a special case: in order to extend the current behaviour (keeping space sequences together as a `<ws>` token) to all Unicode whitespaces, all you have to do is enumerate them. You needn't worry about updating the rules (as would be the case with adding Unicode variants of e.g. `.`). And [there are not so many of them](https://www.cs.tut.fi/~jkorpela/chars/spaces.html), anyway.

So please, do add support for them.

**Comment by DavidNemeskey** [comment]
Thanks!
