### ISSUE TITLE
Nem utf env? 

### ISSUE THREAD

**Issue by kornai** [dlt-rilmta/quntoken#40]
Docker MacOS 11.0.1 alatt az alábbi hibauzenetet adja: 

cat  lit_hu_dia_Spiro_Gyorgy-Fogsag.xml | sudo docker run -i mtaril/emtsv tok,morph > output.txt
Password:
/usr/local/lib/python3.8/site-packages/sklearn/linear_model/least_angle.py:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
(...)
  max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
/usr/local/lib/python3.8/site-packages/sklearn/linear_model/least_angle.py:1738: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, positive=False):
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/quntoken/quntoken.py", line 31, in stdin_writer
    stdin.writelines(inp)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcf6' in position 36: surrogates not allowed

A bemenõ file mnsz_v2.0.4/xml_clean/lit/dia alól van

**Comment by dlazesz** [comment]
Bár sosem dolgoztam az MNSZ XML-el, de úgy tudom, hogy Latin-2 kódolású és a kiterjesztés alapján XML formátumú, míg a Quntoken elvárt bemenete úgyhogy látatlanban azt mondanám, hogy ez lesz a probléma.

**Comment by mittelholcz** [comment]
@dlazesz fején találta a szöget: a quntoken elvárt bemenete sima txt, utf-8 kódolásban, ahogy a README-ben is szerepel (*quntoken reads plain text in UTF-8 ...*).
