### ISSUE TITLE
quntoken filename filename throws  unrecognized arguments error

### ISSUE THREAD

**Issue by cinkova** [dlt-rilmta/quntoken#47]
Dear developers, 
please tell me how to get rid of this fundamental error: 
`cinkova@lundi21:~$ quntoken rpha12_plaintext.txt test.tsv`

`usage: quntoken [-h] [-f FORM] [-m MODE] [-w] [-v]`

`quntoken: error: unrecognized arguments: rpha12_plaintext.txt test.tsv`

`cinkova@lundi21:~$ quntoken 'rpha12_plaintext.txt' 'test.tsv'`
The input file is located directly in my home folder. 

This actually helped (by ChatGPT): `cat /home/cinkova/rpha12_plaintext.txt | quntoken`. Maybe it would be helpful for beginner users to share this tip in README?

**Comment by sassbalint** [comment]
Thank you for your inquiry.

As [it is stated here](https://github.com/nytud/quntoken#usage), the command line usage is:
```bash
quntoken <input.txt >output.tsv
```

It seems that you just have forgotten to use `<` and `>` for input and output respectively.

Remark: `cat input.txt | quntoken > output.tsv` is essentially the same as `quntoken <input.txt >output.tsv`.

**Comment by cinkova** [comment]
Sorry, I thought that the <> are meta characters around the file name. All clear now. Thank you for your reply. 
Silvie
